title: SPHEREx Calibration Lab Wiki
description: SPHEREx Calibration Lab Wiki
author: SPHEREx Lab Wiki
github: https://github.com/SPHEREx/SPHEREx-lab-tools
about: Entries listed by date.  Navigate by subject, or search.
#disqus_shortname: stackproblems
#google_analytics: UA-XXXXXXXX-Y

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/
  hardware:
    output: true
    permalink: /hardware/:path/
  software:
    output: true
    permalink: /software/:path/

urls:
    - text: Hardware
      url: /hardware/
    - text: Software
      url: /software/
    - text: Projects
      url: /projects/
    - text: Schedules
      url: /schedules/
    - text: Files
      url: /files/
    - text: FAQ
      url: /faq/

url: "https://SPHEREx-lab-tools.github.io"
baseurl: ""
paginate: 30
per_page: 30
paginate_path: "/page/:num/"
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
